name: PHP Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
 
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx (Optional but recommended for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker layers to speed up builds
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t php-hello-world .

      # Optionally push the Docker image to Docker Hub (replace 'your-username/php-hello-world' with your image name)
      - name: Push Docker image to Docker Hub
        run: |
          docker tag php-hello-world your-docker-username/php-hello-world:latest
          docker push your-docker-username/php-hello-world:latest

      # Run the container
      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 php-hello-world

      # Test if the container is running (access index.php)
      - name: Test the PHP application
        run: |
          sleep 5
          curl --fail http://localhost:8080/index.php || exit 1

      # Stop and remove the Docker container after testing
      - name: Clean up Docker container
        run: |
          docker stop $(docker ps -q)
          docker system prune -f
