name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker-compose build

    - name: Run Docker container
      run: docker-compose up -d

    - name: Test the app
      run: |
        sleep 5 # Wait for the container to start
        curl --fail http://localhost:8080

    - name: Stop Docker container
      run: docker-compose down