name: PHP Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          docker build -t php-hello-world .

      - name: Push Docker image to Docker Hub
        run: |
          docker tag php-hello-world my_cicd_docker_one:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/php-hello-world:latest

      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 php-hello-world

      - name: Test the PHP application
        run: |
          sleep 5
          curl --fail http://localhost:8080/index.php || exit 1

      - name: Clean up Docker container
        run: |
          docker stop $(docker ps -q)
          docker system prune -f
